# Generated by Django 5.0.3 on 2024-03-21 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topic_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('upload_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=8, unique=True)),
                ('content_url', models.URLField(max_length=264)),
                ('content_type', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Topics_Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procrastinate.topics')),
                ('upload_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procrastinate.uploads')),
            ],
        ),
    ]
