# Generated by Django 5.0.3 on 2024-03-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procrastinate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='user_id',
        ),
        migrations.AddField(
            model_name='uploads',
            name='username',
            field=models.CharField(default='alejandro', max_length=64),
            preserve_default=False,
        ),
    ]
